
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const BlockLibrary: typeof import("../components/BlockLibrary.vue")['default']
export const ChatPanel: typeof import("../components/ChatPanel.vue")['default']
export const ConfirmHost: typeof import("../components/ConfirmHost.vue")['default']
export const ConstructorPanel: typeof import("../components/ConstructorPanel.vue")['default']
export const DeployModal: typeof import("../components/DeployModal.vue")['default']
export const IntroSplash: typeof import("../components/IntroSplash.vue")['default']
export const ListEditor: typeof import("../components/ListEditor.vue")['default']
export const PageCanvas: typeof import("../components/PageCanvas.vue")['default']
export const StructurePicker: typeof import("../components/StructurePicker.vue")['default']
export const ThemeToggle: typeof import("../components/ThemeToggle.vue")['default']
export const ToastHost: typeof import("../components/ToastHost.vue")['default']
export const BaseBadge: typeof import("../components/base/BaseBadge.vue")['default']
export const BaseButton: typeof import("../components/base/BaseButton.vue")['default']
export const BaseConfirmDialog: typeof import("../components/base/BaseConfirmDialog.vue")['default']
export const BaseDropdown: typeof import("../components/base/BaseDropdown.vue")['default']
export const BaseInput: typeof import("../components/base/BaseInput.vue")['default']
export const BaseModal: typeof import("../components/base/BaseModal.vue")['default']
export const BaseSelect: typeof import("../components/base/BaseSelect.vue")['default']
export const BaseSkeleton: typeof import("../components/base/BaseSkeleton.vue")['default']
export const BaseTabs: typeof import("../components/base/BaseTabs.vue")['default']
export const BaseTextarea: typeof import("../components/base/BaseTextarea.vue")['default']
export const BaseToast: typeof import("../components/base/BaseToast.vue")['default']
export const EditorsCatalogFilterEditor: typeof import("../components/editors/CatalogFilterEditor.vue")['default']
export const EditorsContactMapEditor: typeof import("../components/editors/ContactMapEditor.vue")['default']
export const EditorsCustomContentEditor: typeof import("../components/editors/CustomContentEditor.vue")['default']
export const EditorsFaqEditor: typeof import("../components/editors/FaqEditor.vue")['default']
export const EditorsFooterEditor: typeof import("../components/editors/FooterEditor.vue")['default']
export const EditorsGalleryEditor: typeof import("../components/editors/GalleryEditor.vue")['default']
export const EditorsGrid3ColEditor: typeof import("../components/editors/Grid3ColEditor.vue")['default']
export const EditorsHeaderEditor: typeof import("../components/editors/HeaderEditor.vue")['default']
export const EditorsHeroEditor: typeof import("../components/editors/HeroEditor.vue")['default']
export const EditorsLeadFormEditor: typeof import("../components/editors/LeadFormEditor.vue")['default']
export const EditorsPricingEditor: typeof import("../components/editors/PricingEditor.vue")['default']
export const EditorsStatsEditor: typeof import("../components/editors/StatsEditor.vue")['default']
export const EditorsTestimonialsEditor: typeof import("../components/editors/TestimonialsEditor.vue")['default']
export const EditorsTextImageEditor: typeof import("../components/editors/TextImageEditor.vue")['default']
export const EditorsEditorRegistry: typeof import("../components/editors/editorRegistry")['default']
export const CartButton: typeof import("../../site-blocks/components/CartButton.vue")['default']
export const CartDrawer: typeof import("../../site-blocks/components/CartDrawer.vue")['default']
export const EditableText: typeof import("../../site-blocks/components/EditableText.vue")['default']
export const ImagePlaceholder: typeof import("../../site-blocks/components/ImagePlaceholder.vue")['default']
export const ItemActionButton: typeof import("../../site-blocks/components/ItemActionButton.vue")['default']
export const LeadFormFields: typeof import("../../site-blocks/components/LeadFormFields.vue")['default']
export const LeadModal: typeof import("../../site-blocks/components/LeadModal.vue")['default']
export const SectionRenderer: typeof import("../../site-blocks/components/SectionRenderer.vue")['default']
export const SiteOverlays: typeof import("../../site-blocks/components/SiteOverlays.vue")['default']
export const BlockRegistry: typeof import("../../site-blocks/components/blockRegistry")['default']
export const CatalogFilter: typeof import("../../site-blocks/components/blocks/CatalogFilter/CatalogFilter.vue")['default']
export const CatalogFilterGrid: typeof import("../../site-blocks/components/blocks/CatalogFilter/variants/CatalogFilterGrid.vue")['default']
export const CatalogFilterList: typeof import("../../site-blocks/components/blocks/CatalogFilter/variants/CatalogFilterList.vue")['default']
export const CatalogFilterShowcase: typeof import("../../site-blocks/components/blocks/CatalogFilter/variants/CatalogFilterShowcase.vue")['default']
export const ContactMap: typeof import("../../site-blocks/components/blocks/ContactMap/ContactMap.vue")['default']
export const ContactMapCards: typeof import("../../site-blocks/components/blocks/ContactMap/variants/ContactMapCards.vue")['default']
export const ContactMapCentered: typeof import("../../site-blocks/components/blocks/ContactMap/variants/ContactMapCentered.vue")['default']
export const ContactMapSplit: typeof import("../../site-blocks/components/blocks/ContactMap/variants/ContactMapSplit.vue")['default']
export const CustomContent: typeof import("../../site-blocks/components/blocks/CustomContent/CustomContent.vue")['default']
export const CustomContentStandard: typeof import("../../site-blocks/components/blocks/CustomContent/variants/CustomContentStandard.vue")['default']
export const Faq: typeof import("../../site-blocks/components/blocks/Faq/Faq.vue")['default']
export const FaqAccordion: typeof import("../../site-blocks/components/blocks/Faq/variants/FaqAccordion.vue")['default']
export const FaqPlain: typeof import("../../site-blocks/components/blocks/Faq/variants/FaqPlain.vue")['default']
export const FaqTwoColumns: typeof import("../../site-blocks/components/blocks/Faq/variants/FaqTwoColumns.vue")['default']
export const Footer: typeof import("../../site-blocks/components/blocks/Footer/Footer.vue")['default']
export const FooterColumns: typeof import("../../site-blocks/components/blocks/Footer/variants/FooterColumns.vue")['default']
export const FooterMinimal: typeof import("../../site-blocks/components/blocks/Footer/variants/FooterMinimal.vue")['default']
export const FooterSimple: typeof import("../../site-blocks/components/blocks/Footer/variants/FooterSimple.vue")['default']
export const Gallery: typeof import("../../site-blocks/components/blocks/Gallery/Gallery.vue")['default']
export const GalleryGrid: typeof import("../../site-blocks/components/blocks/Gallery/variants/GalleryGrid.vue")['default']
export const GalleryMasonry: typeof import("../../site-blocks/components/blocks/Gallery/variants/GalleryMasonry.vue")['default']
export const GallerySlider: typeof import("../../site-blocks/components/blocks/Gallery/variants/GallerySlider.vue")['default']
export const Grid3Col: typeof import("../../site-blocks/components/blocks/Grid3Col/Grid3Col.vue")['default']
export const Grid3ColCards: typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColCards.vue")['default']
export const Grid3ColCompactGrid: typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColCompactGrid.vue")['default']
export const Grid3ColIconRows: typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColIconRows.vue")['default']
export const Grid3ColIconTop: typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColIconTop.vue")['default']
export const Grid3ColMinimalList: typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColMinimalList.vue")['default']
export const Grid3ColPhotoCards: typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColPhotoCards.vue")['default']
export const Header: typeof import("../../site-blocks/components/blocks/Header/Header.vue")['default']
export const HeaderCentered: typeof import("../../site-blocks/components/blocks/Header/variants/HeaderCentered.vue")['default']
export const HeaderMinimal: typeof import("../../site-blocks/components/blocks/Header/variants/HeaderMinimal.vue")['default']
export const HeaderSplit: typeof import("../../site-blocks/components/blocks/Header/variants/HeaderSplit.vue")['default']
export const HeaderStandard: typeof import("../../site-blocks/components/blocks/Header/variants/HeaderStandard.vue")['default']
export const Hero: typeof import("../../site-blocks/components/blocks/Hero/Hero.vue")['default']
export const HeroCentered: typeof import("../../site-blocks/components/blocks/Hero/variants/HeroCentered.vue")['default']
export const HeroGradient: typeof import("../../site-blocks/components/blocks/Hero/variants/HeroGradient.vue")['default']
export const HeroMinimal: typeof import("../../site-blocks/components/blocks/Hero/variants/HeroMinimal.vue")['default']
export const HeroOverlay: typeof import("../../site-blocks/components/blocks/Hero/variants/HeroOverlay.vue")['default']
export const HeroSplit: typeof import("../../site-blocks/components/blocks/Hero/variants/HeroSplit.vue")['default']
export const LeadForm: typeof import("../../site-blocks/components/blocks/LeadForm/LeadForm.vue")['default']
export const LeadFormCard: typeof import("../../site-blocks/components/blocks/LeadForm/variants/LeadFormCard.vue")['default']
export const LeadFormInline: typeof import("../../site-blocks/components/blocks/LeadForm/variants/LeadFormInline.vue")['default']
export const LeadFormSplit: typeof import("../../site-blocks/components/blocks/LeadForm/variants/LeadFormSplit.vue")['default']
export const Pricing: typeof import("../../site-blocks/components/blocks/Pricing/Pricing.vue")['default']
export const PricingCards: typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingCards.vue")['default']
export const PricingHighlight: typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingHighlight.vue")['default']
export const PricingMinimal: typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingMinimal.vue")['default']
export const PricingTable: typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingTable.vue")['default']
export const Stats: typeof import("../../site-blocks/components/blocks/Stats/Stats.vue")['default']
export const StatsBigNumbers: typeof import("../../site-blocks/components/blocks/Stats/variants/StatsBigNumbers.vue")['default']
export const StatsCards: typeof import("../../site-blocks/components/blocks/Stats/variants/StatsCards.vue")['default']
export const StatsRow: typeof import("../../site-blocks/components/blocks/Stats/variants/StatsRow.vue")['default']
export const Testimonials: typeof import("../../site-blocks/components/blocks/Testimonials/Testimonials.vue")['default']
export const TestimonialsAvatarsRow: typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsAvatarsRow.vue")['default']
export const TestimonialsCards: typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsCards.vue")['default']
export const TestimonialsQuotes: typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsQuotes.vue")['default']
export const TestimonialsSingleFeatured: typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsSingleFeatured.vue")['default']
export const TextImage: typeof import("../../site-blocks/components/blocks/TextImage/TextImage.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Motion: typeof import("@vueuse/motion")['MotionComponent']
export const MotionGroup: typeof import("@vueuse/motion")['MotionGroupComponent']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyBlockLibrary: LazyComponent<typeof import("../components/BlockLibrary.vue")['default']>
export const LazyChatPanel: LazyComponent<typeof import("../components/ChatPanel.vue")['default']>
export const LazyConfirmHost: LazyComponent<typeof import("../components/ConfirmHost.vue")['default']>
export const LazyConstructorPanel: LazyComponent<typeof import("../components/ConstructorPanel.vue")['default']>
export const LazyDeployModal: LazyComponent<typeof import("../components/DeployModal.vue")['default']>
export const LazyIntroSplash: LazyComponent<typeof import("../components/IntroSplash.vue")['default']>
export const LazyListEditor: LazyComponent<typeof import("../components/ListEditor.vue")['default']>
export const LazyPageCanvas: LazyComponent<typeof import("../components/PageCanvas.vue")['default']>
export const LazyStructurePicker: LazyComponent<typeof import("../components/StructurePicker.vue")['default']>
export const LazyThemeToggle: LazyComponent<typeof import("../components/ThemeToggle.vue")['default']>
export const LazyToastHost: LazyComponent<typeof import("../components/ToastHost.vue")['default']>
export const LazyBaseBadge: LazyComponent<typeof import("../components/base/BaseBadge.vue")['default']>
export const LazyBaseButton: LazyComponent<typeof import("../components/base/BaseButton.vue")['default']>
export const LazyBaseConfirmDialog: LazyComponent<typeof import("../components/base/BaseConfirmDialog.vue")['default']>
export const LazyBaseDropdown: LazyComponent<typeof import("../components/base/BaseDropdown.vue")['default']>
export const LazyBaseInput: LazyComponent<typeof import("../components/base/BaseInput.vue")['default']>
export const LazyBaseModal: LazyComponent<typeof import("../components/base/BaseModal.vue")['default']>
export const LazyBaseSelect: LazyComponent<typeof import("../components/base/BaseSelect.vue")['default']>
export const LazyBaseSkeleton: LazyComponent<typeof import("../components/base/BaseSkeleton.vue")['default']>
export const LazyBaseTabs: LazyComponent<typeof import("../components/base/BaseTabs.vue")['default']>
export const LazyBaseTextarea: LazyComponent<typeof import("../components/base/BaseTextarea.vue")['default']>
export const LazyBaseToast: LazyComponent<typeof import("../components/base/BaseToast.vue")['default']>
export const LazyEditorsCatalogFilterEditor: LazyComponent<typeof import("../components/editors/CatalogFilterEditor.vue")['default']>
export const LazyEditorsContactMapEditor: LazyComponent<typeof import("../components/editors/ContactMapEditor.vue")['default']>
export const LazyEditorsCustomContentEditor: LazyComponent<typeof import("../components/editors/CustomContentEditor.vue")['default']>
export const LazyEditorsFaqEditor: LazyComponent<typeof import("../components/editors/FaqEditor.vue")['default']>
export const LazyEditorsFooterEditor: LazyComponent<typeof import("../components/editors/FooterEditor.vue")['default']>
export const LazyEditorsGalleryEditor: LazyComponent<typeof import("../components/editors/GalleryEditor.vue")['default']>
export const LazyEditorsGrid3ColEditor: LazyComponent<typeof import("../components/editors/Grid3ColEditor.vue")['default']>
export const LazyEditorsHeaderEditor: LazyComponent<typeof import("../components/editors/HeaderEditor.vue")['default']>
export const LazyEditorsHeroEditor: LazyComponent<typeof import("../components/editors/HeroEditor.vue")['default']>
export const LazyEditorsLeadFormEditor: LazyComponent<typeof import("../components/editors/LeadFormEditor.vue")['default']>
export const LazyEditorsPricingEditor: LazyComponent<typeof import("../components/editors/PricingEditor.vue")['default']>
export const LazyEditorsStatsEditor: LazyComponent<typeof import("../components/editors/StatsEditor.vue")['default']>
export const LazyEditorsTestimonialsEditor: LazyComponent<typeof import("../components/editors/TestimonialsEditor.vue")['default']>
export const LazyEditorsTextImageEditor: LazyComponent<typeof import("../components/editors/TextImageEditor.vue")['default']>
export const LazyEditorsEditorRegistry: LazyComponent<typeof import("../components/editors/editorRegistry")['default']>
export const LazyCartButton: LazyComponent<typeof import("../../site-blocks/components/CartButton.vue")['default']>
export const LazyCartDrawer: LazyComponent<typeof import("../../site-blocks/components/CartDrawer.vue")['default']>
export const LazyEditableText: LazyComponent<typeof import("../../site-blocks/components/EditableText.vue")['default']>
export const LazyImagePlaceholder: LazyComponent<typeof import("../../site-blocks/components/ImagePlaceholder.vue")['default']>
export const LazyItemActionButton: LazyComponent<typeof import("../../site-blocks/components/ItemActionButton.vue")['default']>
export const LazyLeadFormFields: LazyComponent<typeof import("../../site-blocks/components/LeadFormFields.vue")['default']>
export const LazyLeadModal: LazyComponent<typeof import("../../site-blocks/components/LeadModal.vue")['default']>
export const LazySectionRenderer: LazyComponent<typeof import("../../site-blocks/components/SectionRenderer.vue")['default']>
export const LazySiteOverlays: LazyComponent<typeof import("../../site-blocks/components/SiteOverlays.vue")['default']>
export const LazyBlockRegistry: LazyComponent<typeof import("../../site-blocks/components/blockRegistry")['default']>
export const LazyCatalogFilter: LazyComponent<typeof import("../../site-blocks/components/blocks/CatalogFilter/CatalogFilter.vue")['default']>
export const LazyCatalogFilterGrid: LazyComponent<typeof import("../../site-blocks/components/blocks/CatalogFilter/variants/CatalogFilterGrid.vue")['default']>
export const LazyCatalogFilterList: LazyComponent<typeof import("../../site-blocks/components/blocks/CatalogFilter/variants/CatalogFilterList.vue")['default']>
export const LazyCatalogFilterShowcase: LazyComponent<typeof import("../../site-blocks/components/blocks/CatalogFilter/variants/CatalogFilterShowcase.vue")['default']>
export const LazyContactMap: LazyComponent<typeof import("../../site-blocks/components/blocks/ContactMap/ContactMap.vue")['default']>
export const LazyContactMapCards: LazyComponent<typeof import("../../site-blocks/components/blocks/ContactMap/variants/ContactMapCards.vue")['default']>
export const LazyContactMapCentered: LazyComponent<typeof import("../../site-blocks/components/blocks/ContactMap/variants/ContactMapCentered.vue")['default']>
export const LazyContactMapSplit: LazyComponent<typeof import("../../site-blocks/components/blocks/ContactMap/variants/ContactMapSplit.vue")['default']>
export const LazyCustomContent: LazyComponent<typeof import("../../site-blocks/components/blocks/CustomContent/CustomContent.vue")['default']>
export const LazyCustomContentStandard: LazyComponent<typeof import("../../site-blocks/components/blocks/CustomContent/variants/CustomContentStandard.vue")['default']>
export const LazyFaq: LazyComponent<typeof import("../../site-blocks/components/blocks/Faq/Faq.vue")['default']>
export const LazyFaqAccordion: LazyComponent<typeof import("../../site-blocks/components/blocks/Faq/variants/FaqAccordion.vue")['default']>
export const LazyFaqPlain: LazyComponent<typeof import("../../site-blocks/components/blocks/Faq/variants/FaqPlain.vue")['default']>
export const LazyFaqTwoColumns: LazyComponent<typeof import("../../site-blocks/components/blocks/Faq/variants/FaqTwoColumns.vue")['default']>
export const LazyFooter: LazyComponent<typeof import("../../site-blocks/components/blocks/Footer/Footer.vue")['default']>
export const LazyFooterColumns: LazyComponent<typeof import("../../site-blocks/components/blocks/Footer/variants/FooterColumns.vue")['default']>
export const LazyFooterMinimal: LazyComponent<typeof import("../../site-blocks/components/blocks/Footer/variants/FooterMinimal.vue")['default']>
export const LazyFooterSimple: LazyComponent<typeof import("../../site-blocks/components/blocks/Footer/variants/FooterSimple.vue")['default']>
export const LazyGallery: LazyComponent<typeof import("../../site-blocks/components/blocks/Gallery/Gallery.vue")['default']>
export const LazyGalleryGrid: LazyComponent<typeof import("../../site-blocks/components/blocks/Gallery/variants/GalleryGrid.vue")['default']>
export const LazyGalleryMasonry: LazyComponent<typeof import("../../site-blocks/components/blocks/Gallery/variants/GalleryMasonry.vue")['default']>
export const LazyGallerySlider: LazyComponent<typeof import("../../site-blocks/components/blocks/Gallery/variants/GallerySlider.vue")['default']>
export const LazyGrid3Col: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/Grid3Col.vue")['default']>
export const LazyGrid3ColCards: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColCards.vue")['default']>
export const LazyGrid3ColCompactGrid: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColCompactGrid.vue")['default']>
export const LazyGrid3ColIconRows: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColIconRows.vue")['default']>
export const LazyGrid3ColIconTop: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColIconTop.vue")['default']>
export const LazyGrid3ColMinimalList: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColMinimalList.vue")['default']>
export const LazyGrid3ColPhotoCards: LazyComponent<typeof import("../../site-blocks/components/blocks/Grid3Col/variants/Grid3ColPhotoCards.vue")['default']>
export const LazyHeader: LazyComponent<typeof import("../../site-blocks/components/blocks/Header/Header.vue")['default']>
export const LazyHeaderCentered: LazyComponent<typeof import("../../site-blocks/components/blocks/Header/variants/HeaderCentered.vue")['default']>
export const LazyHeaderMinimal: LazyComponent<typeof import("../../site-blocks/components/blocks/Header/variants/HeaderMinimal.vue")['default']>
export const LazyHeaderSplit: LazyComponent<typeof import("../../site-blocks/components/blocks/Header/variants/HeaderSplit.vue")['default']>
export const LazyHeaderStandard: LazyComponent<typeof import("../../site-blocks/components/blocks/Header/variants/HeaderStandard.vue")['default']>
export const LazyHero: LazyComponent<typeof import("../../site-blocks/components/blocks/Hero/Hero.vue")['default']>
export const LazyHeroCentered: LazyComponent<typeof import("../../site-blocks/components/blocks/Hero/variants/HeroCentered.vue")['default']>
export const LazyHeroGradient: LazyComponent<typeof import("../../site-blocks/components/blocks/Hero/variants/HeroGradient.vue")['default']>
export const LazyHeroMinimal: LazyComponent<typeof import("../../site-blocks/components/blocks/Hero/variants/HeroMinimal.vue")['default']>
export const LazyHeroOverlay: LazyComponent<typeof import("../../site-blocks/components/blocks/Hero/variants/HeroOverlay.vue")['default']>
export const LazyHeroSplit: LazyComponent<typeof import("../../site-blocks/components/blocks/Hero/variants/HeroSplit.vue")['default']>
export const LazyLeadForm: LazyComponent<typeof import("../../site-blocks/components/blocks/LeadForm/LeadForm.vue")['default']>
export const LazyLeadFormCard: LazyComponent<typeof import("../../site-blocks/components/blocks/LeadForm/variants/LeadFormCard.vue")['default']>
export const LazyLeadFormInline: LazyComponent<typeof import("../../site-blocks/components/blocks/LeadForm/variants/LeadFormInline.vue")['default']>
export const LazyLeadFormSplit: LazyComponent<typeof import("../../site-blocks/components/blocks/LeadForm/variants/LeadFormSplit.vue")['default']>
export const LazyPricing: LazyComponent<typeof import("../../site-blocks/components/blocks/Pricing/Pricing.vue")['default']>
export const LazyPricingCards: LazyComponent<typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingCards.vue")['default']>
export const LazyPricingHighlight: LazyComponent<typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingHighlight.vue")['default']>
export const LazyPricingMinimal: LazyComponent<typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingMinimal.vue")['default']>
export const LazyPricingTable: LazyComponent<typeof import("../../site-blocks/components/blocks/Pricing/variants/PricingTable.vue")['default']>
export const LazyStats: LazyComponent<typeof import("../../site-blocks/components/blocks/Stats/Stats.vue")['default']>
export const LazyStatsBigNumbers: LazyComponent<typeof import("../../site-blocks/components/blocks/Stats/variants/StatsBigNumbers.vue")['default']>
export const LazyStatsCards: LazyComponent<typeof import("../../site-blocks/components/blocks/Stats/variants/StatsCards.vue")['default']>
export const LazyStatsRow: LazyComponent<typeof import("../../site-blocks/components/blocks/Stats/variants/StatsRow.vue")['default']>
export const LazyTestimonials: LazyComponent<typeof import("../../site-blocks/components/blocks/Testimonials/Testimonials.vue")['default']>
export const LazyTestimonialsAvatarsRow: LazyComponent<typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsAvatarsRow.vue")['default']>
export const LazyTestimonialsCards: LazyComponent<typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsCards.vue")['default']>
export const LazyTestimonialsQuotes: LazyComponent<typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsQuotes.vue")['default']>
export const LazyTestimonialsSingleFeatured: LazyComponent<typeof import("../../site-blocks/components/blocks/Testimonials/variants/TestimonialsSingleFeatured.vue")['default']>
export const LazyTextImage: LazyComponent<typeof import("../../site-blocks/components/blocks/TextImage/TextImage.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyMotion: LazyComponent<typeof import("@vueuse/motion")['MotionComponent']>
export const LazyMotionGroup: LazyComponent<typeof import("@vueuse/motion")['MotionGroupComponent']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
